[project]
name = "nl2pln"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dspy>=3.0.4",
    "mlflow>=3.6.0",
    "mm2chainer",
    "pytest>=9.0.1",
]

[tool.uv.sources]
mm2chainer = { path = "../MM2Chainer", editable = true }
